### ISSUE TITLE
캘린더에서 delay되어 표시되는 문제

### ISSUE THREAD

**Issue by J1wanSeo** [puang-network/caucalendar#23]
안녕하세요, 해당 파일 잘 사용중에 있는 사용자입니다.

다름이 아닌 구글 캘린더에 해당 캘린더를 추가하게 되면 하루씩 당겨져서 나타나는 버그가 있습니다.

어디에서 문제가 발생되는 것인지 확인할 수 없어서 여기에 남기게 되었습니다.

항상 잘 이용중에 있습니다, 감사드립니다.

**Comment by LiteHell** [comment]
커밋 214cd7142666b37f3fd57cd9ef4b765be94d95cc 에서 수정했습니다. 버그 제보해주서셔 감사합니다.
